name: didit_sdk
description: Didit Identity Verification SDK for Flutter. Wraps native iOS and Android SDKs for document scanning, NFC passport reading, face verification, and liveness detection.
version: 3.4.4
homepage: https://didit.me
repository: https://github.com/didit-protocol/sdk-flutter
issue_tracker: https://github.com/didit-protocol/sdk-flutter/issues

environment:
  sdk: ^3.11.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.didit.sdk.sdk_flutter
        pluginClass: SdkFlutterPlugin
      ios:
        pluginClass: SdkFlutterPlugin
