// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrtjmxZJh7bJl3JLIs9O3HM1_z1Svf1cI',
    appId: '1:1002686729184:web:5b04796592942d245d7985',
    messagingSenderId: '1002686729184',
    projectId: 'kabayansync',
    authDomain: 'kabayansync.firebaseapp.com',
    storageBucket: 'kabayansync.firebasestorage.app',
    measurementId: 'G-8SLFWDP18C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTUU8K4pFt5J9fAZEaCkIbeBYpwr-sPDQ',
    appId: '1:1002686729184:android:7ab67da97c0e38fd5d7985',
    messagingSenderId: '1002686729184',
    projectId: 'kabayansync',
    storageBucket: 'kabayansync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABVkMQTo21oe32C1soTMu7k_0_yetXu9s',
    appId: '1:1002686729184:ios:5ba5b21f58d239f65d7985',
    messagingSenderId: '1002686729184',
    projectId: 'kabayansync',
    storageBucket: 'kabayansync.firebasestorage.app',
    iosBundleId: 'com.example.kbsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABVkMQTo21oe32C1soTMu7k_0_yetXu9s',
    appId: '1:1002686729184:ios:5ba5b21f58d239f65d7985',
    messagingSenderId: '1002686729184',
    projectId: 'kabayansync',
    storageBucket: 'kabayansync.firebasestorage.app',
    iosBundleId: 'com.example.kbsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrtjmxZJh7bJl3JLIs9O3HM1_z1Svf1cI',
    appId: '1:1002686729184:web:2fca52ffd205aac15d7985',
    messagingSenderId: '1002686729184',
    projectId: 'kabayansync',
    authDomain: 'kabayansync.firebaseapp.com',
    storageBucket: 'kabayansync.firebasestorage.app',
    measurementId: 'G-3BZ19NS7BH',
  );
}
